name: Blazewars
version: 2.0
author: Aspire
main: com.stelch.games2.BlazeWars.Main
api-version: 1.13
commands:
    mct:
        description: Map Creator Tools V1
    game:
        description: Arcade Administration command